export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>TodoList</title>
  <base href="https://OMKAR9395.github.io/Todo-List-Angular/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.todo-container[_ngcontent-ng-c213711874]{max-width:400px;margin:20px auto;padding:15px;border:1px solid #ddd;border-radius:5px;text-align:center}h1[_ngcontent-ng-c213711874]{font-size:20px;color:#333}input[_ngcontent-ng-c213711874]{width:70%;padding:8px;margin-bottom:10px;border:1px solid #ccc;border-radius:5px;font-size:14px}button[_ngcontent-ng-c213711874]{padding:8px 12px;margin-top:5px;border:none;border-radius:5px;cursor:pointer;font-size:14px}button[_ngcontent-ng-c213711874]:hover{opacity:.8}button.add[_ngcontent-ng-c213711874]{background-color:#28a745;color:#fff}button.delete[_ngcontent-ng-c213711874]{background-color:#dc3545;color:#fff}ul[_ngcontent-ng-c213711874]{list-style:none;padding:0}li[_ngcontent-ng-c213711874]{background:#f9f9f9;padding:8px;margin:5px 0;border-radius:5px;display:flex;justify-content:space-between;align-items:center}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["input","compositionstart","compositionend","click"],["blur"]);</script>
  <app-root ng-version="19.2.1" _nghost-ng-c213711874 ngh="0" ng-server-context="ssg"><div _ngcontent-ng-c213711874 class="todo-container"><h1 _ngcontent-ng-c213711874>Todo List</h1><input _ngcontent-ng-c213711874 type="text" placeholder="Enter New Task" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><button _ngcontent-ng-c213711874 class="add" jsaction="click:;">Add Task</button><!----></div></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-66ER7YMC.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"7":"t0"},"c":{"7":[]}}]}</script></body></html>`;